# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Amandine Dupays
email: amandine.dupays@gmail.com
description: >
  DÃ©veloppeuse web front-end, travaillant en JavaScript et HTML5/CSS3.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.amandinedupays.fr" # the base hostname & protocol for your site
twitter_username: AmandineDupays
github_username:  adupays
linkedin_username:  amandinedupays

# Build settings
markdown: kramdown

exclude: ["blog.md"]
